### ISSUE TITLE
Phase 1 feedback/issues to be addressed

### ISSUE THREAD

**Issue by achamely** [OmniLayer/omniexplorer#104]
Tracking of identified issues to address from phase 1 rollout

**Comment by germanf** [comment]
- [ ] Styling/formatting numbers to include `,` for thousands separators with user’s locale and/or language and/or local preference setting to choose commas and dots appropriately.
- [ ] Use same timezone for all timestamps.
- [ ] Remove QR code and add a button near the address to display the QR code in a modal.
- [ ] All address displays should include a QR code button and a copy button.
- [ ] Tx displays should also have a copy button.
- [ ] Add title to search page, e.g. what was entered in the search field
- [ ] Notify user when rate limit is reached.
- [ ] Property in Grant Property Tokens, Revoke Property Tokens, Freeze Property Tokens. For consistency, we should use <verb> <object>.

**Comment by marvgmail** [comment]
- [ ] Use same timezone for all timestamps. Otherwise user has to do the adjustment in his head in order to compare the times.
- [ ] searching for coin only shows prod eco props, but there are a lot of test properties with coin in the name. searching for test returns both prod and test eco props
- [ ] Use user’s locale and/or language and/or local preference setting to choose commas and dots appropriately
- [ ] To save display space, remove QR code and add a button near the address to display the QR code in a modal. Also, all address displays should include a QR code button and a copy button. Tx displays should also have a copy button. (I know - I’ve mentioned some of these before.)
- [ ] what value is added by the word Simple in Simple Send? Same question about Property in Grant Property Tokens, Revoke Property Tokens, Freeze Property Tokens. For consistency, we should use <verb> <object> wherever possible: Send, Grant, Revoke, Freeze, Offer, …, e.g. Send Tokens.
or, if it’s clear, just use the verb
- [ ] The search page has no title, e.g. what was entered in the search field. Could also highlight the searched item in the results, e.g. the “ether” in TetherUS
- [ ] Try searching for 14, then 14p. First one finds a property, second one finds an address. Should 14 find both??
- [ ] first time I clicked on both Properties > Property List it said nothing found. The second try (for each, I think) now displays the expected lists.
- [ ] searching for coin only shows prod eco props, but there are a lot of test properties with coin in the name. searching for test returns both prod and test eco props
- [ ] change MetaDex to OmniDEx
- [ ] an unconfirmed tx will move in the tx list when it is confirmed. We need to determine best way to tell the user that has happened. So when he goes back to the tx list after looking at tx details, the user will know that tx is no longer unconfirmed.
- [ ] make tx list format cleaner & mmore concise. (I have some ideas.)
- [ ] use one page for address, combine & clean up data from search & address pages
- [ ] the address page doesn't include any "As of" information
- [ ] on the address page, highlight that address in the tx list so it's easy to see if Sends are from or to that address
- [ ] consider showing resulting balance(s) for each tx
- [ ] on address page, add "From" and "To" as filter choices; that could be local js to do that
- [ ] change the default property icon to something less distracting, or don't display anything
- [ ] change link color for any link that's been clicked

**Comment by achamely** [comment]
[ ] Hide horizontal scroll bars on search page when not needed
