### ISSUE TITLE
Omni API rate limit

### ISSUE THREAD

**Issue by jtorre-circle** [OmniLayer/omniexplorer#154]
I would like to use the OMNI API for a project I am working on but the rate limit is weighing me down. I was wondering if there was a paid service I could use in order to increase my rate limit.

**Comment by achamely** [comment]
@jtorre-circle Not at the moment but we are looking into such service/offering.  
Can you describe a bit more your project so we can try to better understand the use case and we can try to help you streamline your calls

**Comment by jtorre-circle** [comment]
Thanks for getting back to me. I’m trying to look at transactions for customers in my db that had an issue when they were trying to withdrawal from their account. I want to be able to either process their withdrawal or cancel it based on the data I would get by searching through this API. Searches are given a date range and an amount range.

**Comment by achamely** [comment]
@jtorre-circle a few things jump out immediately which may help
You should not need to search the tx history of the address/user by amount. 
When you process a customer withdrawal the omnicore-cli returns the txid of the transaction.  As long as you are recording that txid in your db you can always reference it for later. 
That txid will either be on the blockchain or not. If it is not, it may be lingering in your client, due to chained utxo spends or something else causing the delayed broadcast, but the txid is unique that doesn't change and you can always check your client mempool to determine if the tx is pending or just gone (getrawtransaction txid, getmempoolentry txid)

That should significantly speed up what you are checking and eliminate the need to cycle through the history of an address

**Comment by jtorre-circle** [comment]
Thank you, unfortunately we are dealing with transactions for which the txid was not know due to an error that occurred during the withdrawal.

**Comment by achamely** [comment]
@jtorre-circle try the [omni_listtransactions command](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions) 
It can list the recent 'count' of transactions sent/received by your wallet

**Comment by dexX7** [comment]
> It can list the recent 'count' of transactions sent/received by your wallet

... as well as watch-only addresses. ;)
