### ISSUE TITLE
USDT在區塊鍊卡住

### ISSUE THREAD

**Issue by qaz89392009** [OmniLayer/omniexplorer#208]
這是我的地址1GnLs1u6v1pu9nsFZ7MiF7J4Z9XiiRing1
我有一筆USDT 11164  昨晚卡在確認卡到現在都還沒有確認
能幫我處理一下嗎

**Comment by achamely** [comment]
@qaz89392009 Omniexplorer is just an explorer and does not have any control over any of the transactions/addresses you see. The unconfirmed tx on your address is unconfirmed because it was sent with a network fee that is much lower than the current network. Depending on where the transaction was sent from or to you can see if its possible the sender or receiver can perform a child pays for parent tx to increase its priority. if not you will have to wait for the network to pick it up
